# Generated by Django 5.0.6 on 2024-08-13 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='price',
        ),
        migrations.RemoveField(
            model_name='package',
            name='requests',
        ),
        migrations.RemoveField(
            model_name='packageday',
            name='package',
        ),
        migrations.CreateModel(
            name='PackageOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='packages.package')),
            ],
        ),
        migrations.AddField(
            model_name='packageday',
            name='package_offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='packages.packageoffer'),
            preserve_default=False,
        ),
    ]
