# Generated by Django 5.0.6 on 2024-08-13 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourday',
            name='tour',
        ),
        migrations.AddField(
            model_name='tourday',
            name='tour_offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tours.tour'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TourOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_offer', to='tours.tour')),
            ],
        ),
    ]
