# Generated by Django 5.0.6 on 2024-08-13 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_remove_tourday_tour_tourday_tour_offer_touroffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourday',
            name='tour_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.touroffer'),
        ),
    ]
