# Generated by Django 5.0.6 on 2024-08-14 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
        ('packages', '0003_remove_package_price_remove_package_requests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagebooking',
            name='package',
        ),
        migrations.AddField(
            model_name='packagebooking',
            name='package_offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='packages.packageoffer'),
            preserve_default=False,
        ),
    ]
